image: registry.gitlab.com/razd-cli/razd-debian-slim:latest


build:
  script:
    - echo "=== Verify installations ==="
    - mise --version
    - razd --version
    
    - echo "=== Install tools and dependencies ==="
    - mise install
    - razd install
    
    - echo "=== Razd build ==="
    - razd build