name: Test mise Integration with Razd

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: razd-cli/razd-action-mise@v1
      
      - name: Build with razd
        run: |
          razd --version
          razd install
          razd build
